### ISSUE TITLE
Back button takes back to tutorial

### ISSUE THREAD

**Issue by manparvesh** [IdeaTrackerPlus/IdeaTrackerPlus#1]
Description
-------------------------------------------
The app takes back to the last intro page after completing it.

What are the steps to reproduce this issue?
-------------------------------------------
1. Install for the first time
2. After the introduction, press back

What happens?
-------------
Takes back to the intro.

What were you expecting to happen?
----------------------------------
App should exit

What versions of software are you using?
----------------------------------------
**App version:** 0.1

**Comment by ikakus** [comment]
Hi @manparvesh , I would like to work on this issue

**Comment by manparvesh** [comment]
@ikakus sure
