### ISSUE TITLE
Bigger heading

### ISSUE THREAD

**Issue by manparvesh** [IdeaTrackerPlus/IdeaTrackerPlus#10]
Description
-------------------------------------------
Heading text should be a bit bigger than the ideas

**Comment by KrishAmal** [comment]
Hi @manparvesh , i'd like to work on this

**Comment by manparvesh** [comment]
@KrishAmal you're welcome to work on this issue. Thanks for your interest

**Comment by KrishAmal** [comment]
Hey , do i have to wait till October 1 to open the pull request so that it will be considered for the Hacktoberfest ?

**Comment by manparvesh** [comment]
No, I think your PR needs to be accepted in October for that. You can work on this in the mean time.

**Comment by KrishAmal** [comment]
Ahh , very well.
