### ISSUE TITLE
View idea details

### ISSUE THREAD

**Issue by manparvesh** [IdeaTrackerPlus/IdeaTrackerPlus#13]
Description
-------------------------------------------
Show idea details first and provision to `Edit` and `Delete` specific idea

- [x] Match primary color. similar to edit idea dialog.
- [x] Show `TextView` instead of disabled `EditText` for idea and note.
- [x] Show only selected priority

**Comment by ikakus** [comment]
Hi @manparvesh , I would like to work on this issue
