### ISSUE TITLE
Edit button in idea

### ISSUE THREAD

**Issue by manparvesh** [IdeaTrackerPlus/IdeaTrackerPlus#14]
Description
-------------------------------------------
The button text to save an idea after changing it is displayed as 'edit'.

What are the steps to reproduce this issue?
-------------------------------------------
1. Edit an idea

What happens?
-------------
The save button should be displayed

What were you expecting to happen?
----------------------------------
Instead of save, edit button is displayed

What versions of software are you using?
----------------------------------------
**App version:** 0.1

**Comment by mukund54** [comment]
Hi @manparvesh , I would like to work on this issue
