### ISSUE TITLE
Secondary color in add / edit dialog

### ISSUE THREAD

**Issue by manparvesh** [IdeaTrackerPlus/IdeaTrackerPlus#15]
Description
-------------------------------------------
Secondary color in add / edit dialog is not changed 

What are the steps to reproduce this issue?
-------------------------------------------
1. Add / edit an idea

What happens?
-------------
default secondary color is displayed

What were you expecting to happen?
----------------------------------
selected secondary color should be displayed

What versions of software are you using?
----------------------------------------
**App version:** 0.1

**Comment by Viciouss** [comment]
I'd like to work on this. The problem is the cursor color. You can only set it in the layout file. I would prefer not to use reflection for this because it usually breaks at some point. How about setting it to black no matter which secondary color is selected, is that okay with you?

**Comment by manparvesh** [comment]
@Viciouss :+1:
