### ISSUE TITLE
Right bar opens without a project 

### ISSUE THREAD

**Issue by manparvesh** [IdeaTrackerPlus/IdeaTrackerPlus#2]
Description
-------------------------------------------
Right bar opens without a project 

What are the steps to reproduce this issue?
-------------------------------------------
1. When there are no projects, swipe from the right side

What happens?
-------------
The settings bar will open

What were you expecting to happen?
----------------------------------
Shouldn't open

What versions of software are you using?
----------------------------------------
**App version:** 0.1

**Comment by ikakus** [comment]
Hi @manparvesh , I would like to work on this issue

**Comment by manparvesh** [comment]
@ikakus sure
