### ISSUE TITLE
Adding ideas after sorting

### ISSUE THREAD

**Issue by manparvesh** [IdeaTrackerPlus/IdeaTrackerPlus#21]
Description
-------------------------------------------
There is no default criteria to organize the ideas. After sorting, ideas are simply added at the end of the list.

What should happen?
----------------------------------
List should be sorted every time an idea is added (by time added or the criteria set by user)

**Comment by Viciouss** [comment]
Currently you can only sort by priority. Should a new option be created to sort by creation time as part of this issue? Or should the list just always be sorted by priority after adding an element?

**Comment by Viciouss** [comment]
I shouldn't write comments late in the evening, just saw that #20 solves this issue. There is a dependency then and it should be taken into account if any of the issues is to be resolved.

**Comment by manparvesh** [comment]
@Viciouss no actually this is a different issue. I want the list to be sorted always. Currently when I add to a sorted list, it is added at the end which makes it not sorted.

**Comment by ikakus** [comment]
@manparvesh I can work on this
