### ISSUE TITLE
Add button text is not changed

### ISSUE THREAD

**Issue by manparvesh** [IdeaTrackerPlus/IdeaTrackerPlus#4]
Description
-------------------------------------------
Add button text is not changed after changing text color

What are the steps to reproduce this issue?
-------------------------------------------
1. change color of text

What happens?
-------------
Plus button text is not changed

What were you expecting to happen?
----------------------------------
Should be changed

What versions of software are you using?
----------------------------------------
**App version:** 0.1

**Comment by ikakus** [comment]
Hi @manparvesh , I would like to work on this issue

**Comment by manparvesh** [comment]
@ikakus sure
