### ISSUE TITLE
Add Continuous Integration

### ISSUE THREAD

**Issue by manparvesh** [IdeaTrackerPlus/IdeaTrackerPlus#45]
Feature description:
-------------------
Add Continuous Integration server like Travis CI

Any ideas on how to implement it?
---------------------------------
- [Continuous Integration and Code Coverage in Android using Travis CI](https://medium.com/@multidots/continuous-integration-and-code-coverage-in-android-using-travis-ci-64e6b92f5d48)

**Comment by smcintosh881** [comment]
I can help with this

**Comment by manparvesh** [comment]
@smcintosh881 sure, thanks!

**Comment by naushad-madakiya** [comment]
Hi @manparvesh @smcintosh881 Can I work on this if it has not done yet?

**Comment by smcintosh881** [comment]
@naushad-madakiya sure

**Comment by naushad-madakiya** [comment]
Hi, There are issues with gradle dependencies, as there are multiple libraries used within a project. Few of the libraries are using higher version of support libraries and few are lower. It's necessary to have the same version for support libraries, if not it produces the lint error and which stops the build generation of travis CI.

@manparvesh let me know if I can start with updating the dependencies, build tool version and target SDK.

**Comment by naushad-madakiya** [comment]
Travis Logs:

>Execution failed for task ':app:lint'.  Lint found errors in the project; aborting build.
  Fix the issues identified by lint, or add the following to your build script to proceed with errors:
android {
      lintOptions {
          abortOnError false
      }
 }


Dependencies:
>compile 'com.android.support:appcompat-v7:23.4.0'
+--- com.github.iammert:MaterialIntroView:1.5.2
|    +--- com.android.support:appcompat-v7:23.1.1 -> 24.0.0 (*)
|    \--- com.android.support:cardview-v7:23.1.0 -> 23.4.0

**Comment by manparvesh** [comment]
@naushad-madakiya sure, please just make sure that everything works as well in the app after updating the dependencies and there are no errors.

**Comment by naushad-madakiya** [comment]
@manparvesh adding Travis CI isn't seemed easy as of now, because of the different dependencies we have added. First, we will have to replace dependencies and create the native functionality like using a design support lib and stuff. 

@smcintosh881 can you suggest something?

failing builds: https://travis-ci.org/naushad-madakiya/IdeaTrackerPlus/builds

**Comment by naushad-madakiya** [comment]
Travis CI is working and merged, Thanks to @t04glovern 

Travis: https://travis-ci.org/IdeaTrackerPlus/IdeaTrackerPlus
