### ISSUE TITLE
Use constants instead of magic numbers

### ISSUE THREAD

**Issue by Viciouss** [IdeaTrackerPlus/IdeaTrackerPlus#50]
Description
-------------------------------------------
The code for the drawer setup uses magic numbers to determine behaviour (may also apply somewhere else)

What are the steps to reproduce this issue?
-------------------------------------------
1. Open the class MainActivity
2. Look at the method setUpDrawers()
3. Try to follow the setup of the drawers and/or the switch case statement which handles the logic

What happens?
-------------
You will get dizzy scrolling up and down to see which number corresponds to which item.

`new PrimaryDrawerItem().withIdentifier(1)` (what is 1?)

What were you expecting to happen?
----------------------------------
You should be able to read the code like a book without the need to scroll back.

`new PrimaryDrawerItem().withIdentifier(ID_PRIMARY_COLOR)`

What versions of software are you using?
----------------------------------------
**App version:** 0.1

**Comment by Viciouss** [comment]
In the method MainActivity.onItemClick there are several cases that are handled by the right drawer now. See case 21 to case 26.  I guess they weren't removed when the logic was moved from the left to the right drawer. Should I remove them while cleaning this up or should I create an extra issue/commit?

**Comment by manparvesh** [comment]
@Viciouss nice catch

**Comment by manparvesh** [comment]
@naushad-madakiya please write an explanation before closing a PR
